### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by astorfi**
Adding the plot_roc function to facenet.py for plotting the ROC curve.

### CODE REVIEW

**Comment by astorfi** [comment]
Adding the plot_roc function to facenet.py for plotting the ROC curve.

**Comment by davidsandberg** [comment]
I think this would fit better in validate_on_lfw.py. If you move it to that file, after the lines
```
            print('Accuracy: %1.3f+-%1.3f' % (np.mean(accuracy), np.std(accuracy)))
            print('Validation rate: %2.5f+-%2.5f @ FAR=%2.5f' % (val, val_std, far))
```
I will be happy to merge it.
Thanks!

**Comment by astorfi** [comment]
The conflict has been resolved!
You mean I should move the whole function there?

**Comment by davidsandberg** [comment]
Yes.

**Comment by astorfi** [comment]
Plotting ROC function added to validate_on_lfw.py file.

**Comment by davidsandberg** [comment]
Sorry for beeing unclear. I meant just move the lines 
```
   auc = metrics.auc(fpr, tpr)
   print('AUC=: %1.3f' % auc)
   eer = brentq(lambda x: 1. - x - interpolate.interp1d(fpr, tpr)(x), 0., 1.)
   print('EER=: %1.3f' % eer)
```
to right after the print lines and before the plot_roc.

**Comment by astorfi** [comment]
No problem ... I just update it again.
Thanks for the prompt response.

**Comment by astorfi** [comment]
validate_on_lfw.py and facenet.py have been updated.

**Comment by davidsandberg** [comment]
Looks good! Thanks!

**Comment by astorfi** [comment]
My pleasure. Thanks to you indeed for your great repository.

**Pull request merged**
