### PR TITLE
Adding support for Python3 and Windows

### PR DESCRIPTION
**Pull request by iTaybb**
Please note that I had to change the path delimiter to be "|" instead of ":", since it's breaking windows code.

### CODE REVIEW

**Comment by davidsandberg** [comment]
Hi,
Could the path delimiter be ";" instead of "|" since ";" is the path separator in windows?
I think that would work fine in linux as well.

**Comment by iTaybb** [comment]
Yeah it surely can.

**Comment by davidsandberg** [comment]
Great!
I'm thinking of an easy way to add an assert that `:` is not used as separator (since people will probably not notice the update and be puzzled). But not sure how to do it in a nice way.

**Comment by iTaybb** [comment]
Well, to just change it into ";" will break compatibility of course.
Since ":" is a delimiter between the drive letter and the relative drive path inside, if the part before the ":" is one char long, it's safe to assume it's a windows path.
But yeah, it's rather ugly.

**Comment by davidsandberg** [comment]
What about supporting both delimiters, i.e. change
```
for path in paths.split(':'):
```
to
```
for path in paths.split(':;'):
```
and also change the default delimiter to `;`.
Then it would still work with the old (and new) delimiter on linux and it would work with the new delimiter on windows.

**Comment by davidsandberg** [comment]
I take that back. It will obviously not work for windows since it will still split between the drive and the rest of the path.

**Pull request closed without merging**
