### PR TITLE
Face clustering script

### PR DESCRIPTION
**Pull request by MaartenBloemen**
Added a small script as an example on how to cluster together similar faces based on the distance matrix.
@davidsandberg do you prefer that I place the script in the `tmp` folder instead of `src` folder?

### CODE REVIEW

**Comment by itsviral** [comment]
@MaartenBloemen  I have little knowledge of facet . I have been heavily using dlib and openCV. I am trying to run cluster.py but some how I don't understand the input parameters of the program.

what you mean by the  "meta_file and ckpt_file or a model protobuf (.pb) file')" . Can you give example or structure? Is cluster.py the solution of unsupervised face clustering? For Instance I have folder called "FACES" and it contain 1000 images of faces. Will it cluster similar faces together in one folder as google photo app does?
My apologies for asking basic. question . Many Thanks.

**Comment by MaartenBloemen** [comment]
Hi @itsviral,
Basic example of how to run the script: `python src/cluster.py /path/to/model/dir/ /path/to/folder/containing/FACES/ /path/to/output/dir/` this is the most basic way to run the script.

* You can train a model (meta_file and ckpt_file or protobuf file) as described on the [wiki](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1) or you can download a pretrained model [here](https://drive.google.com/file/d/0B5MzpY9kBtDVZ2RpVDYwWmxoSUk/edit).
* By default the script will save all the clusters into different folders in the output dir you choose. If you only want the largest cluster to be saved you can add `--largest_cluster_only` to the command.

Some other things you can fiddle around with:
* You can set the minimum size of a cluster using `--min_cluster_size n` where "n" is a round positive number. All clusters smaller than the chosen size will be ignored.
* If the clusters aren't totally correct you can change the threshold by using `--cluster_threshold n` where "n" is a positive decimal number between 0 and 2, where 0 = 100% and 2 =  0%.

Hope this clears things up for you. If you have any other questions let me know.

**Comment by davidsandberg** [comment]
Thanks for this!! Moved the script to the 'contributed' folder.

**Comment by MaartenBloemen** [comment]
@davidsandberg Thank you for this awesome project! 😃

**Comment by dyshuang** [comment]
Hi, @MaartenBloemen . I'm now working on the face clustering and your script has given a lot of help to me, thank you so much!
However, I just do some test of your code which includes 100 pictures of 3 different person. With your script, it said only one cluster which means that all the picture is from the same person?
I wonder the reason of this result...is it because that the sample size I used is too small?
Looking forward to your reply~

**Comment by MaartenBloemen** [comment]
Hey @dyshuang , thanks for your interest in my face clustering script! Could you show me the command you used to run the script?

**Comment by dyshuang** [comment]
Hello! @MaartenBloemen , thank you a lot for your reply! 
This is my command to run the script：
python /Users/dyshuang/facenet/contributed/cluster.py /Users/dyshuang/facenet/src/models/20170512-110547 /Users/dyshuang/facenet/data/images/test /Users/dyshuang/facenet/data/images/testop 

the path to model folder: /Users/dyshuang/facenet/src/models/20170512-11054
the path to folder containing to FACES:/Users/dyshuang/facenet/data/images/test
the path to to output dir: /Users/dyshuang/facenet/data/images/testop 

And the result is like this:
No of clusters: 1
Saving all clusters
Cluster 0: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24...100 ]

Any help will be appreciated.

**Comment by MaartenBloemen** [comment]
Hey @dyshuang , Kinda weird that the script puts it in one cluster, everything in your command is correct. The only difference is that I tested with a slightly older protobuf model. I will test with the one you used. But i'm afraid I won't be able to do that until next week when I have access to my deep learning computer again.

**Comment by dyshuang** [comment]
Hello!@MaartenBloemen, so nice for your quick reply.
I am wondering the reason maybe that the pictures I used was  too similar with each other, as I just create a folder of the picture of me and my friends. 
I will test some other people, maybe different age and skin.^_^

**Comment by MaartenBloemen** [comment]
Hi @dyshuang , the script is working for me as it should. Did you by any chance put this in comment:
```python
print('')
            # Print distance matrix
            print('Distance matrix')
            print('    ', end='')
            for i in range(nrof_images):
                print('    %1d     ' % i, end='')
            print('')
            for i in range(nrof_images):
                print('%1d  ' % i, end='')
                for j in range(nrof_images):
                    dist = np.sqrt(np.sum(np.square(np.subtract(emb[i, :], emb[j, :]))))
                    matrix[i][j] = dist
                    print('  %1.4f  ' % dist, end='')
                print('')

print('')
```

**Comment by nono1981** [comment]
@dyshuang maybe the 'cluster_threshold' argument issue. Try it with smaller value, such as 0.85.

**Comment by RaviRaaja** [comment]
@MaartenBloemen  I used cluster.py to clsuter images where i used dlib to crop and align image with dimension of 160,160,3 every face images. Issue is after DBscan all images are pushed into same directory as result and i have experimented by normalizing images using facenet,prewhiten() from facenet.py still i face same issue. is there any optimal threshold to check dbscan ??

**Comment by yashwantram97** [comment]
> Hello! @MaartenBloemen , thank you a lot for your reply!
> This is my command to run the script：
> python /Users/dyshuang/facenet/contributed/cluster.py /Users/dyshuang/facenet/src/models/20170512-110547 /Users/dyshuang/facenet/data/images/test /Users/dyshuang/facenet/data/images/testop
> 
> the path to model folder: /Users/dyshuang/facenet/src/models/20170512-11054
> the path to folder containing to FACES:/Users/dyshuang/facenet/data/images/test
> the path to to output dir: /Users/dyshuang/facenet/data/images/testop
> 
> And the result is like this:
> No of clusters: 1
> Saving all clusters
> Cluster 0: [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24...100 ]
> 
> Any help will be appreciated.

*****EVEN I AM FACING THE SAME PROBLEM, CAN ANYONE HELP OR GUIDE ME TO HOW TO SOLVE THIS PROBLEM?*****

I m using the pretrained model to cluster the faces. I will insert 100 photos or 10 different persons in the apropriate folder. Then i directly run python cluster.py model_dir data_dir output_dir and the result i m getting is only one cluster.


Thank you

**Comment by yashwantram97** [comment]
Yea it worked for me... changing theshold value to 0.85 and making --is_aligned to False will make it work

**Pull request merged**
