### PR TITLE
bulk_detect_face first draft implementation (~30% speed up)

### PR DESCRIPTION
**Pull request by artur-trzesiok**
detect_and_align_comparsion

### CODE REVIEW

**Comment by artur-trzesiok** [comment]
Profiling raport:
Tested on 16 images in bulk:
image

**Comment by davidsandberg** [comment]
Excellent work!! Thanks!

**Comment by artur-trzesiok** [comment]
Thanks! Right now cost of detection is mainly located  in cv2.resize(img, (sz[1], sz[0]), interpolation=cv2.INTER_AREA)  function. I tried to change interpolation method to nearest neighbor but in some cases that provide a bad results.

**Comment by mgy89** [comment]
good job!  @artur-trzesiok 
you did the optimization I just need.

another idea:
If we use pure GPU optimization, it will be faster.

**Comment by flymer** [comment]
Hi!
Is the bulk_detect_face function working? I call it giving as an input a list of images and it returns a list of Nones. (Images that contain faces that can be detected with the detect_face function).
Cheers

**Comment by YanzheL** [comment]
I have the same issue as @flymer

**Comment by YanzheL** [comment]
I have the same issue as @flymer
```
boxes = detect_face.bulk_detect_face(img, 48, self.pnet, self.rnet, self.onet, self.threshold, self.factor)
```
returns
```
[None, None,...,None]
```
But the image contain faces that can be detected with the original detect_face function

**Comment by lciruelo** [comment]
@YanzheL did you solve the result [None, None,...,None]?

**Comment by abhisheksgumadi** [comment]
The solution to getting None is to send a very small number for the "detection_window_size_ratio" parameter in bulk_detect_face. I sent a value of 0.001 and I was able to get the same result as a single detection.

**Pull request merged**
